// WHAT A RUN LEAVES BEHIND, and who clears it.
//
// The suite writes into `_tmp/` so it never touches a developer's own saves
// or profile (`launch.ts`) — but `_tmp/` is not the suite's alone: it is the
// project's scratch folder, full of screenshots and dumps somebody made on
// purpose. So nothing here wipes `_tmp`. It removes the two folders a LAUNCH
// creates and nothing outside the suite reads.
//
// This runs BOTH before and after a run (playwright.config.ts), and the
// before half is the one that matters: a run that is killed, or a single spec
// driven by hand, leaves state behind with no teardown to collect it, and the
// next run has to start clean regardless of how the last one ended.
//
// It is not tidiness. `e2e/001/load.spec.ts` raises a campaign, finds it in
// LOAD GAME by its team name and asserts the slot reads `0/26` — so a save
// under that same name left by an earlier run, at whatever position that run
// walked it to, fails a spec nobody touched. That happened, and the failure
// points at LOAD GAME rather than at the leftover.

import { rmSync } from 'node:fs'

import { PROFILE_DIR, SAVE_DIR } from './launch'

/**
 * Clear what a launched app wrote: the save slots and the Electron profile.
 *
 * Both are recreated on demand — `src/main/saves.ts` makes the folder before
 * it writes a slot, and Electron makes the profile at startup — so removing
 * them is safe at either end of a run.
 *
 * The phase chain's `.env` (`PHASE_ENV`) is deliberately NOT cleared: it is
 * the handover between phases, it is regenerated by phase 000, and keeping it
 * is what lets a later phase be run warm on its own.
 */
export default function clearScratch(): void {
  rmSync(SAVE_DIR, { recursive: true, force: true })
  rmSync(PROFILE_DIR, { recursive: true, force: true })
}
